### PR TITLE
Updated Three Side visualisation 

### PR DESCRIPTION
**Pull request by anchouls**
#131 

Unnecessary highlighting between the windows remains. 

Screenshot 2023-03-31 at 03 12 13

In the case of Two Side and More Side, we have a `SimpleDiffViewer` that has a `SimpleTextDiffProvider` that has a `compareRange` function that takes a `DiffComputer diffComputer` that determines the changes to be highlighted. If `diffComputer == null`, the `SimpleTextDiffProvider` finds the changes itself. 

In the case of Three Side, we have `SimpleThreesideDiffViewer`, which has a `SimpleThreesideTextDiffProvider`, which hasn't function that takes something to override the changes somehow.  That's why `SimpleThreesideTextDiffProvider` always finds the changes that need to be highlighted by itself. 

Currently `SimpleThreesideDiffViewer.getChanges()` returns `unmodifiableList`, so nothing can be changed here.

### CODE REVIEW

**Comment by onewhl** [comment]
@anchouls maybe we can get away from the idea of showing three-sided diff for such types of refactoring and come up with something that would be more intuitive? The example on the screenshot doesn't look intuitive. What if we show the old class on the left side with highlighted removed items with grey color, and the new class on the right side highlighted with green color? Please, checkout on RefactorInsight version of the 2021 year and check how it worked.

**Comment by anchouls** [comment]
@onewhl I tried different ways to visualise it:

Screenshot 2023-04-14 at 22 39 01

Screenshot 2023-04-14 at 21 37 01

Screenshot 2023-04-14 at 22 31 12

A hint could potentially be added to indicate that the class contains a reference to the extract class (since it is not visualized).

**Comment by onewhl** [comment]
@anchouls the first one is the best!

**Comment by anchouls** [comment]
@onewhl Updated the visualization as in the first picture. Hints are already there (I didn't notice them)

**Comment by anchouls** [comment]
@onewhl It finds Move Method refactorings and therefore shows the hints. At the same time, the Move Method refactorings are not shown in the list of refactorings, since they all belong to the Extract Class refactoring.
Screenshot 2023-04-20 at 18 50 41

**Comment by onewhl** [comment]
@anchouls I meant a hint above the extracted class with information about the classes it was extracted from.
`Extracted from A.java, B.java.`

**Review by onewhl — CHANGES_REQUESTED** [review]
@anchouls cool, thank you! Please, investigate if it's possible to add a hint above the extracted class with information about the classes it was extracted from.
`Extracted from A, B, C classes.`

**Comment by anchouls** [comment]
@onewhl I added this hint to the standard diff window. How to add hints to the refactoring diff window, I haven't figured out yet.

**Review by onewhl — APPROVED** [review]

**Pull request merged**
